/**
 * Library-style extension build: Rollup + esbuild → plain ESM.
 *
 * Why plain ESM with bare imports?
 * The host injects a native `<script type="importmap">` (generated by
 * `scripts/build-nop-shared.mjs`) mapping every `SHARED_MODULE_NAMES` name
 * to a facade file that re-exports the host's own instances. Because the
 * extension bundle keeps those names as bare external specifiers, the
 * browser resolves them through the import map to the host's react/ui
 * modules — exactly one instance, no duplicate-React breakage, and the
 * artifact is standard ESM consumable by any toolchain.
 *
 * Output layout (matched by the host and the Java deploy contract):
 *   dist/
 *     extension.json          ← id/name/version/entry/styleAssets/assets
 *     assets/index.js         ← the ESM entry (extension.json.entry)
 *     assets/<original>       ← runtime `new URL` references
 *     assets/<hashed>         ← stable names for Java pre-injection
 *     locales/...             ← copied from public/ when present
 *     public/**               ← copied verbatim
 */

import { cpSync, existsSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { rollup } from 'rollup';
import esbuild from 'rollup-plugin-esbuild';

import { assetHashedName, extensionManifestPlugin } from './manifest-plugin.mjs';
import { SHARED_MODULE_NAMES } from './contract.mjs';

/**
 * @typedef {Object} BuildExtensionOptions
 * @property {string} id - Extension id (must equal the deploy directory name).
 * @property {string} name - Human-readable extension name.
 * @property {string} [version] - Extension version (optional).
 * @property {string} [entry] - Entry module relative to root (default `src/index.ts`).
 * @property {string} [root] - Project root (default `process.cwd()`).
 * @property {string} [outDir] - Output directory (default `dist`).
 * @property {boolean} [minify] - Minify with esbuild (default true).
 * @property {boolean} [sourcemap] - Emit sourcemaps (default false).
 * @property {{ [key: string]: string }} [define] - esbuild `define` map.
 */

/**
 * @param {BuildExtensionOptions} options
 * @returns {Promise<{ outDir: string; entryFile: string; manifest: Record<string, unknown> }>}
 */
export async function buildExtension({
  id,
  name,
  version,
  entry = 'src/index.ts',
  root = process.cwd(),
  outDir = 'dist',
  minify = true,
  sourcemap = false,
  define,
}) {
  if (typeof id !== 'string' || !/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(id)) {
    throw new TypeError(`buildExtension: invalid id '${String(id)}'`);
  }
  if (typeof name !== 'string' || name.length === 0) {
    throw new TypeError('buildExtension: name is required');
  }

  const rootAbs = resolve(root);
  const outAbs = resolve(rootAbs, outDir);
  const entryAbs = resolve(rootAbs, entry);

  if (!existsSync(entryAbs)) {
    throw new Error(`buildExtension: entry not found: ${entryAbs}`);
  }

  rmSync(outAbs, { recursive: true, force: true });
  mkdirSync(outAbs, { recursive: true });

  /** @type {Set<string>} */
  const extraStyleAssets = new Set();

  const cssAssetPattern = /\.css(\?.*)?$/;
  const assetImportPattern = /\.(svg|png|jpe?g|gif|webp|ico|woff2?|ttf|eot)(\?.*)?$/;

  /**
   * Static asset imports (`import url from './x.svg'`) emit the file into
   * dist/assets and export a runtime URL relative to the bundle location —
   * correct both on a dev asset server and in the deployed
   * `extensions/<id>/` directory.
   *
   * @type {import('rollup').Plugin}
   */
  const assetImportPlugin = {
    name: 'extension-asset-imports',
    resolveId(source, importer) {
      if (assetImportPattern.test(source) || cssAssetPattern.test(source)) {
        return importer ? resolve(dirname(importer), source) : resolve(source);
      }
      return null;
    },
    load(id) {
      if (cssAssetPattern.test(id)) {
        if (!existsSync(id)) {
          throw new Error(`buildExtension: css file not found: ${id}`);
        }
        const content = readFileSync(id, 'utf8');
        const hashed = assetHashedName(id);
        this.emitFile({ type: 'asset', fileName: `assets/${hashed}`, source: content });
        return '';
      }
      if (assetImportPattern.test(id)) {
        if (!existsSync(id)) {
          throw new Error(`buildExtension: asset file not found: ${id}`);
        }
        const hashed = assetHashedName(id);
        this.emitFile({
          type: 'asset',
          fileName: `assets/${hashed}`,
          source: readFileSync(id),
        });
        // Runtime URL relative to the bundle (import.meta.url is provided by
        // SystemJS and matches the deployed extensions/<id>/ location).
        return `export default new URL("./assets/${hashed}", import.meta.url).href;`;
      }
      return null;
    },
    generateBundle(_outputOptions, bundle) {
      for (const [fileName, output] of Object.entries(bundle)) {
        if (output.type === 'asset' && fileName.endsWith('.css')) {
          extraStyleAssets.add(`./${fileName}`);
        }
      }
    },
  };

  const bundle = await rollup({
    input: entryAbs,
    external: [...SHARED_MODULE_NAMES],
    plugins: [
      esbuild({
        tsconfig: existsSync(resolve(rootAbs, 'tsconfig.json'))
          ? resolve(rootAbs, 'tsconfig.json')
          : undefined,
        target: 'es2022',
        jsx: 'automatic',
        minify,
        ...(define ? { define } : {}),
      }),
      assetImportPlugin,
      extensionManifestPlugin({ id, name, version, entry, extraStyleAssets }),
    ],
    onwarn(warning, warn) {
      if (warning.code === 'UNRESOLVED_IMPORT') {
        throw new Error(
          `buildExtension: unresolved import '${warning.id}' — if it is a host-shared ` +
            `module, add it to SHARED_MODULE_NAMES; ` +
            `otherwise install it in this project.`,
        );
      }
      warn(warning);
    },
  });

  await bundle.write({
    dir: outAbs,
    format: 'es',
    entryFileNames: 'assets/index.js',
    assetFileNames: 'assets/[name]-[hash][extname]',
    sourcemap,
    externalLiveBindings: false,
  });
  await bundle.close();

  // Copy public/** (locales, static assets) next to the bundle, like Vite does.
  const publicDir = resolve(rootAbs, 'public');
  if (existsSync(publicDir)) {
    cpSync(publicDir, outAbs, { recursive: true });
  }

  const manifest = JSON.parse(
    readFileSync(resolve(outAbs, 'extension.json'), 'utf8'),
  );

  return { outDir: outAbs, entryFile: resolve(outAbs, 'assets/index.js'), manifest };
}