#!/usr/bin/env node
/**
 * `nop-extension-dev` — official dev tooling for building nop-chaos
 * extensions without host source.
 *
 * Commands:
 *   dev-in-host  Reverse-proxy the deployed host and inject extension sources
 *                into every HTML response (no host source, no host rebuild).
 *   serve        Static asset server with CORS for built extension artifacts.
 *   inject       Inject the extension-source script into an HTML file
 *                (stdin/file -> stdout) for manual DevTools/override flows.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { HOST_API_VERSION, HOST_API_VERSION_GLOBAL, SHARED_MODULE_NAMES } from './contract.mjs';
import { injectExtensionSources } from './inject.mjs';
import { buildExtension } from './build.mjs';
import { startDevInHostProxy } from './proxy.mjs';
import { startStaticServer } from './serve.mjs';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(readFileSync(resolve(packageRoot, 'package.json'), 'utf8'));

const HELP = `
nop-extension-dev v${pkg.version} — extension development without host source

Usage:
  nop-extension-dev dev-in-host --backend <origin> [--extension <id>=<url>]... [options]
  nop-extension-dev serve --dir <dist> [options]
  nop-extension-dev build --id <id> --name <name> [options]
  nop-extension-dev inject --html <file> [--extension <id>=<url>]...

Commands:
  dev-in-host   Proxy the real host (e.g. nop-entropy) and inject extension
                sources via window.__NOP_EXTENSIONS__ before host bootstrap.
                Browse the proxy URL for the full in-host debugging loop.
                Loaded entries must be absolute http(s) URLs served with CORS
                (Vite dev does by default; 'serve' does too). The host's
                native import map (generated by scripts/build-nop-shared.mjs)
                resolves the bundle's bare shared imports to the host's
                react/ui instances. Legacy '.system.js' entries are loaded
                through SystemJS for backward compatibility.
      --backend <origin>   backend origin, e.g. http://127.0.0.1:8080
      --extension <id=url> repeatable: id and entry URL to inject
      --port <n>           proxy port (default 5174)
      --host <host>        bind host (default 127.0.0.1)
      --verbose            log every request

  build         Build the extension into a deployable plain-ESM bundle
                (dist/assets/index.js + extension.json + assets).
                Produces the layout consumed by the host and by nop-web-site
                (extensions/<id>/). Keeps SHARED_MODULE_NAMES external: the
                host's native import map resolves them to the host's runtime
                modules (single React/UI instances).
      --id <id>            extension id (equals the deploy directory name)
      --name <name>        human-readable extension name
      --version <version>  extension version (optional)
      --entry <path>       entry module relative to root (default src/index.ts)
      --root <dir>         project root (default cwd)
      --out <dir>          output directory (default dist)
      --no-minify          keep readable output
      --sourcemap          emit sourcemaps

  serve         Serve built extension artifacts with CORS enabled.
      --dir <path>         directory to serve (extension build output)
      --port <n>           port (default 4180; 0 = ephemeral)
      --host <host>        bind host (default 127.0.0.1)
      --no-cors            disable Access-Control-Allow-Origin: *
      --verbose            log every request

  inject        Print an HTML document with the extension-source script
                injected (after <head>), to stdout.
      --html <file>        input HTML file (defaults to stdin)
      --extension <id=url> repeatable

Global:
  -h, --help     show this help
  -v, --version  show version

The injected host exposes ${HOST_API_VERSION_GLOBAL} so tooling/UI can verify
the host API version (${HOST_API_VERSION}).
`;

/**
 * @param {string[]} argv
 * @returns {{ command: string; options: Record<string, string | boolean | string[]> }}
 */
function parseArgs(argv) {
  const command = argv[0];
  /** @type {Record<string, string | boolean | string[]>} */
  const options = {};
  const rest = argv.slice(1);

  if (!command || command === '-h' || command === '--help') {
    return { command: 'help', options };
  }

  if (command === '-v' || command === '--version') {
    return { command: 'version', options };
  }

  for (let i = 0; i < rest.length; i += 1) {
    const arg = rest[i];

    if (arg === '-h' || arg === '--help') {
      options.help = true;
      continue;
    }

    if (!arg.startsWith('--')) {
      throw new Error(`Unexpected argument '${arg}' (expected --key value)`);
    }

    const eq = arg.indexOf('=');
    const key = eq >= 0 ? arg.slice(2, eq) : arg.slice(2);
    let value;

    if (eq >= 0) {
      value = arg.slice(eq + 1);
    } else if (i + 1 < rest.length && !rest[i + 1].startsWith('--')) {
      i += 1;
      value = rest[i];
    } else {
      value = true;
    }

    if (key === 'extension') {
      const list = Array.isArray(options.extension) ? options.extension : [];
      list.push(String(value));
      options.extension = list;
    } else if (key in options) {
      throw new Error(`Duplicate option '--${key}'`);
    } else {
      options[key] = value;
    }
  }

  return { command, options };
}

/**
 * Parse `id=url` values from --extension.
 *
 * @param {unknown} raw
 * @returns {Array<{ id: string; url: string }>}
 */
function parseExtensions(raw) {
  const list = Array.isArray(raw) ? raw : raw === undefined ? [] : [raw];

  return list.map((entry, index) => {
    const text = String(entry);
    const eq = text.indexOf('=');

    if (eq <= 0) {
      throw new Error(
        `--extension must be '<id>=<url>' (got '${text}', #${index + 1}); ` +
          `e.g. --extension my-ext=http://127.0.0.1:4180/src/index.ts`,
      );
    }

    const id = text.slice(0, eq);
    const url = text.slice(eq + 1);

    if (!/^https?:\/\//.test(url)) {
      throw new Error(`--extension '${id}': url must be an absolute http(s) URL (got '${url}')`);
    }

    return { id, url };
  });
}

/**
 * @param {string | boolean | string[] | undefined} value
 * @param {string} fallback
 * @returns {string}
 */
function strOption(value, fallback) {
  if (Array.isArray(value)) {
    return typeof value[0] === 'string' && value[0].length > 0 ? value[0] : fallback;
  }
  return typeof value === 'string' && value.length > 0 ? value : fallback;
}

/**
 * @param {string | boolean | string[] | undefined} value
 * @param {number} fallback
 * @returns {number}
 */
function numOption(value, fallback) {
  const raw = Array.isArray(value) ? value[0] : value;
  if (typeof raw !== 'string' || raw.length === 0) {
    return fallback;
  }
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isInteger(parsed) || parsed < 0 || parsed > 65535) {
    throw new Error(`Invalid port '${raw}'`);
  }
  return parsed;
}

async function run() {
  const { command, options } = parseArgs(process.argv.slice(2));

  if (command === 'help' || options.help) {
    process.stdout.write(HELP);
    return;
  }

  if (command === 'version') {
    process.stdout.write(`${pkg.version}\n`);
    return;
  }

  if (command === 'dev-in-host') {
    /** @type {string} */
    const backend = strOption(options.backend, '');
    if (!/^https?:\/\//.test(backend)) {
      throw new Error('dev-in-host requires --backend <origin> (absolute http(s) URL)');
    }

    const extensions = parseExtensions(options.extension);
    if (extensions.length === 0) {
      throw new Error('dev-in-host requires at least one --extension <id>=<url>');
    }

    const port = numOption(options.port, 5174);
    const host = strOption(options.host, '127.0.0.1');
    const verbose = options.verbose === true || options.verbose === 'true';

    const proxy = await startDevInHostProxy({ backend, extensions, port, host, verbose });

    process.stdout.write(
      [
        `nop-extension-dev v${pkg.version} — dev-in-host`,
        `  proxy    : ${proxy.url}`,
        `  backend  : ${backend}`,
        `  host api : ${HOST_API_VERSION_GLOBAL} (expects >= ${HOST_API_VERSION})`,
        `  injected :`,
        ...extensions.map((ext) => `    - ${ext.id} -> ${ext.url}`),
        '',
        `Open ${proxy.url} in the browser. Ctrl+C to stop.`,
        '',
      ].join('\n'),
    );

    process.on('SIGINT', async () => {
      await proxy.close();
      process.exit(0);
    });
    return;
  }

  if (command === 'serve') {
    /** @type {string} */
    const dir = strOption(options.dir, '');
    if (!dir) {
      throw new Error('serve requires --dir <path>');
    }

    const port = numOption(options.port, 4180);
    const host = strOption(options.host, '127.0.0.1');
    const cors = !(options.cors === false || options['no-cors'] === true || options['no-cors'] === 'true');
    const verbose = options.verbose === true || options.verbose === 'true';

    const server = await startStaticServer({ dir, port, host, cors, verbose });

    process.stdout.write(
      [
        `nop-extension-dev v${pkg.version} — serve`,
        `  url  : ${server.url}`,
        `  dir  : ${dir}`,
        `  cors : ${cors ? 'enabled' : 'disabled'}`,
        '',
        'Ctrl+C to stop.',
        '',
      ].join('\n'),
    );

    process.on('SIGINT', async () => {
      await server.close();
      process.exit(0);
    });
    return;
  }

  if (command === 'build') {
    /** @type {string} */
    const id = strOption(options.id, '');
    /** @type {string} */
    const name = strOption(options.name, '');

    if (!id) {
      throw new Error('build requires --id <extension-id>');
    }
    if (!name) {
      throw new Error('build requires --name <extension-name>');
    }

    const root = strOption(options.root, process.cwd());
    // `--outDir` is accepted as an alias of `--out` (used by
    // `pnpm build --outDir <dir>` argument passthrough in tests).
    const outDir = strOption(options.outDir, strOption(options.out, 'dist'));
    const entry = strOption(options.entry, 'src/index.ts');
    const minify = !(options.minify === false || options['no-minify'] === true || options['no-minify'] === 'true');
    const sourcemap = options.sourcemap === true || options.sourcemap === 'true';

    const result = await buildExtension({
      id,
      name,
      version: typeof options.version === 'string' && options.version.length > 0 ? options.version : undefined,
      entry,
      root,
      outDir,
      minify,
      sourcemap,
    });

    process.stdout.write(
      [
        `nop-extension-dev v${pkg.version} — build`,
        `  id      : ${id}`,
        `  name    : ${name}`,
        `  entry   : ${resolve(root, entry)}`,
        `  out     : ${result.outDir}`,
        `  entry   : ./assets/index.js (ESM, ${SHARED_MODULE_NAMES.length} shared modules resolved via host import map)`,
        `  manifest: ${JSON.stringify(result.manifest, null, 2)}`,
        '',
        'Deploy: copy this directory to nop-web-site extensions/<id>/ and the',
        'host (or the Java IndexHtmlProvider) will load it.',
        '',
      ].join('\n'),
    );
    return;
  }

  if (command === 'inject') {
    const extensions = parseExtensions(options.extension);
    if (extensions.length === 0) {
      throw new Error('inject requires at least one --extension <id>=<url>');
    }

    let html;
    if (typeof options.html === 'string' && options.html.length > 0) {
      html = readFileSync(resolve(options.html), 'utf8');
    } else {
      html = readFileSync(0, 'utf8');
    }

    process.stdout.write(injectExtensionSources(html, extensions));
    return;
  }

  throw new Error(`Unknown command '${command}'. Run 'nop-extension-dev --help' for usage.`);
}

run().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  process.stderr.write(`[nop-extension-dev] ${message}\n`);
  process.exitCode = 1;
});